### ISSUE TITLE
Mouse offset and editor resolution problem

### ISSUE THREAD

**Issue by melanie-ramos** [ephtracy/voxel-model#16]
I have only had this problem with my new laptop, it's a dell xps 15 with resolution 1920x1080 and Windows 10. I am using MagicaVoxel 0.99a but it also happens with older versions of the editor, in fullscreen and windowed mode.

Notice the position of the cursor in the first picture and where it is actually pointing (the button on top of it), and also the top and bottom parts of the UI are cut. The hit regions of the UI appear to be offset or scaled smaller than the actual display, as a result in order to click a button I actually have to click underneath it. Very awkward to work with. This appears to be localized to the upper half of the window, as the bottom half of the UI functions as expected (as shown in the second picture). 

![2017-12-23_15-09-04](https://user-images.githubusercontent.com/9472793/34320228-1419ee7c-e7f5-11e7-8d9c-5224b02274b4.png)

![magicavoxel_2017-12-23_15-37-48](https://user-images.githubusercontent.com/9472793/34320301-4e9f3e24-e7f7-11e7-900e-6a05fa7296ba.png)

**Comment by ephtracy** [comment]
From other users' report, it's due to a bug of Intel graphics driver. Try to update driver or use Nvidia/Amd GPU

**Comment by melanie-ramos** [comment]
Hey thanks for the tip, updating my GPU drivers and forcing it to use my GPU worked!
