### ISSUE TITLE
language changing not working on MacOS

### ISSUE THREAD

**Issue by Hurray0** [ephtracy/voxel-model#42]
I move Chinese language `locale.txt`, `dict.txt` to `config/` directory, and `NotoSansSC-Bold.otf` to `config/font/` directory.
But the language changing not working and keeps English.

The `MagicalVoxel.app` version is 0.99.6
System: MacOS Big Sur 11.1

**Comment by Hurray0** [comment]
![WX20210207-141654@2x](https://user-images.githubusercontent.com/6030586/107138409-250eec80-694f-11eb-8db2-2b178011fb6e.png)

**Comment by kchapelier** [comment]
Hi, the feature is currently only implemented in 0.99.6.3 which is only available for Win64 platforms.

See https://twitter.com/ephtracy/status/1343793218777972739 and https://github.com/ephtracy/ephtracy.github.io/releases/tag/0.99.6

**Comment by Hurray0** [comment]
ok, thank you.
I am looking forward to the new version.
