### ISSUE TITLE
Document changes to the file format more thoroughly

### ISSUE THREAD

**Issue by Chryfi** [ephtracy/voxel-model#55]
I am maintaining a project with its own vox parser and since Magicavoxel 0.99.7 the parsing is broken.
I think every developer who wants to use this format would benefit from clear documentation of what changes have been made to the file format.

Other established file formats would also not dare to randomly change things and leave them undocumented. This just makes everyone's life unnecessarily hard and prevents easy use of this file format, not to mention compatibility breaks.

I just can not comprehend, why a software engineer would leave possible compability-breaking changes to their widely used public file format undocumented.

**Comment by ephtracy** [comment]
1. 0.99.7 is currently in the beta stage for testing with new animation features. changes and instability are expected.
2. modification of the format can be seen in the history: https://github.com/ephtracy/voxel-model/commit/29488cf79ce7f3432eb44972743b34958143cb2b
3. I do not guarantee or promise the compatibility or robustness of the program.
