### ISSUE TITLE
Performance issues with backups

### ISSUE THREAD

**Issue by PeterPedro** [ephtracy/voxel-model#59]
Hello so, MV apparently is saving backups of my files every few clicks and that's normally not an issue but I use a good old hard drive and the saving process is pretty slow and the problem with the backups is that every few clicks I have to wait like 10 seconds for the backup to complete (program locks up until complete) which can make the process pretty tedious. So I don't know if I'm missing how to disable backups or maybe there should be an option in there.

0.99.7.1

**Comment by ephtracy** [comment]
Hi, there was an update after the release of 0.99.7.1 to improve the performance of saving files.
can you redownload the program to verify if the issue still exists?
thanks.

**Comment by PeterPedro** [comment]
Thank you I tested it and it works perfect now
